/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

/**
 *
 * @author kickevnzla
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import logic.Cell;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.util.Date;
import java.util.HashSet;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.Timer;

public class WinMinesweeper extends javax.swing.JFrame{
    /**
     * Creates new form winBuscaMinas
     */
    
    public static Cell[][] cells;
    public static int rows, columns, mines;
    public static boolean gameEnded;
    
    Timer timer;
    
    public WinMinesweeper() {
        initComponents();
                
        rows = 9;
        columns = 9;
        mines = 10;
        
        NewGame(rows,columns,mines);
        
        InitialValues();
    }
    
    public void InitialValues() {
        WinMinesweeper.btnFace.setIcon(new ImageIcon(getClass().getResource("/presentation_images/happy-face-icon.png")));
        gameEnded = false;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panWindow = new javax.swing.JPanel();
        panMenu = new javax.swing.JPanel();
        btnFace = new javax.swing.JButton();
        panGame = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mnuEasy = new javax.swing.JMenuItem();
        mnuMedium = new javax.swing.JMenuItem();
        mnuHard = new javax.swing.JMenuItem();
        mnuCustom = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busca Minas Pro");
        setBackground(new java.awt.Color(255, 255, 255));

        panWindow.setBackground(new java.awt.Color(167, 167, 167));
        panWindow.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(251, 251, 251), new java.awt.Color(98, 98, 98)));

        panMenu.setBackground(new java.awt.Color(167, 167, 167));
        panMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(251, 251, 251), new java.awt.Color(98, 98, 98)));

        btnFace.setBackground(new java.awt.Color(167, 167, 167));
        btnFace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/images/happy-face-icon.png"))); // NOI18N
        btnFace.setAlignmentX(0.5F);
        btnFace.setAlignmentY(0.0F);
        btnFace.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(251, 251, 251), new java.awt.Color(98, 98, 98)));
        btnFace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFace.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnFace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMenuLayout = new javax.swing.GroupLayout(panMenu);
        panMenu.setLayout(panMenuLayout);
        panMenuLayout.setHorizontalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFace)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMenuLayout.setVerticalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnFace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        panGame.setBackground(new java.awt.Color(167, 167, 167));
        panGame.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(251, 251, 251), new java.awt.Color(98, 98, 98)));

        javax.swing.GroupLayout panGameLayout = new javax.swing.GroupLayout(panGame);
        panGame.setLayout(panGameLayout);
        panGameLayout.setHorizontalGroup(
            panGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        panGameLayout.setVerticalGroup(
            panGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panWindowLayout = new javax.swing.GroupLayout(panWindow);
        panWindow.setLayout(panWindowLayout);
        panWindowLayout.setHorizontalGroup(
            panWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panWindowLayout.setVerticalGroup(
            panWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(198, 204, 212));

        jMenu1.setText("Juego");

        jMenu3.setText("Dificultad");

        mnuEasy.setText("Principiante");
        mnuEasy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEasyActionPerformed(evt);
            }
        });
        jMenu3.add(mnuEasy);

        mnuMedium.setText("Intermedio");
        mnuMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMediumActionPerformed(evt);
            }
        });
        jMenu3.add(mnuMedium);

        mnuHard.setText("Experto");
        mnuHard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHardActionPerformed(evt);
            }
        });
        jMenu3.add(mnuHard);

        mnuCustom.setText("Personalizado");
        mnuCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCustomActionPerformed(evt);
            }
        });
        jMenu3.add(mnuCustom);

        jMenu1.add(jMenu3);

        jMenuItem1.setText("Juego Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem6.setText("Como jugar");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Nosotros");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCustomActionPerformed

        panGame.removeAll();
        JLabel label = new JLabel("Filas:");
        JLabel label2 = new JLabel("Columnas:");
        JLabel label3 = new JLabel("Minas:");
        JTextField txtRows = new JTextField("");
        JTextField txtColumns = new JTextField("");
        JTextField txtMines = new JTextField("");
        JButton btnStart = new JButton("Iniciar");
        
        label.setBounds(30,10,80,20);
        label2.setBounds(30,40,80,20);
        label3.setBounds(30,70,80,20);
        txtRows.setBounds(100,10,40,20);
        txtColumns.setBounds(100,40,40,20);
        txtMines.setBounds(100,70,40,20);
        btnStart.setBounds(35,110,100,20);
        
        
        panGame.add(label);
        panGame.add(label2);
        panGame.add(label3);
        panGame.add(txtRows);
        panGame.add(txtColumns);
        panGame.add(txtMines);
        panGame.add(btnStart);
        panGame.repaint();
        
        btnStart.addActionListener(new ActionListener() {
			
            public void actionPerformed(ActionEvent e) {
                rows = Integer.parseInt(txtRows.getText());
                columns = Integer.parseInt(txtColumns.getText());;
                mines = Integer.parseInt(txtMines.getText());;
                
                NewGame(rows,columns,mines);
                InitialValues();
            }
        });
    }//GEN-LAST:event_mnuCustomActionPerformed

    
    private void mnuEasyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEasyActionPerformed
        // TODO add your handling code here:        
        rows = 9;
        columns = 9;
        mines = 10;
        
        NewGame(rows,columns,mines);
        
        InitialValues();
    }//GEN-LAST:event_mnuEasyActionPerformed

    private void mnuMediumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMediumActionPerformed
        // TODO add your handling code here:
        rows = 16;
        columns = 16;
        mines = 40;
        
        NewGame(rows,columns,mines);
        
        InitialValues();
    }//GEN-LAST:event_mnuMediumActionPerformed

    private void mnuHardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHardActionPerformed
        // TODO add your handling code here:
        rows = 16;
        columns = 30;
        mines = 99;
        
        NewGame(rows,columns,mines);
        
        InitialValues();
    }//GEN-LAST:event_mnuHardActionPerformed

    private void btnFaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFaceActionPerformed
        // TODO add your handling code here:
        NewGame(rows,columns,mines);
        btnFace.setIcon(new ImageIcon(getClass().getResource("/presentation_images/happy-face-icon.png")));
        InitialValues();
    }//GEN-LAST:event_btnFaceActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        NewGame(rows,columns,mines);
        btnFace.setIcon(new ImageIcon(getClass().getResource("/presentation_images/happy-face-icon.png")));
        InitialValues();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void NewGame(int rows, int columns, int mines) {
        panGame.removeAll();
        panGame.setLayout(new GridLayout(rows,columns));
        Start(rows,columns,mines);
        panGame.repaint();
        this.setSize(0,0);
        this.setSize(columns * 20 + 50,rows * 20 + 130);
    }
    
    public void Start(int rows, int columns, int mines) {
        gameEnded = false;
        
        this.cells = new Cell[rows][columns];
        
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < columns; j++) {
                this.cells[i][j] = new Cell(i,j);
                panGame.add(this.cells[i][j]);
            }
        }
        
        Random rnd = new Random();
        while (mines > 0) {
            Cell cell = cells[rnd.nextInt(rows)][rnd.nextInt(columns)];
            if (!cell.hasMine()) {
                cell.setMine();
                cell.setBackground(Color.red);
                mines--;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinMinesweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinMinesweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinMinesweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinMinesweeper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinMinesweeper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnFace;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem mnuCustom;
    private javax.swing.JMenuItem mnuEasy;
    private javax.swing.JMenuItem mnuHard;
    private javax.swing.JMenuItem mnuMedium;
    private javax.swing.JPanel panGame;
    private javax.swing.JPanel panMenu;
    private javax.swing.JPanel panWindow;
    // End of variables declaration//GEN-END:variables
}
